import { supabase } from './supabase.js';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const app=$('#app'), login=$('#login'), msg=$('#authMsg');
async function session(){const {data}=await supabase.auth.getSession(); if(data.session){const {data:a}=await supabase.from('admin_profiles').select('*').eq('id',data.session.user.id).maybeSingle(); if(a){login.classList.add('hidden');app.classList.remove('hidden');loadCounts();}}}
$('#loginBtn').onclick=async()=>{const {error}=await supabase.auth.signInWithPassword({email:$('#email').value,password:$('#password').value}); if(error)msg.textContent=error.message; else location.reload()};
$('#logout').onclick=async()=>{await supabase.auth.signOut();location.reload()};
$$('aside [data-tab]').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active')});
async function loadCounts(){for(const [t,id] of [['projects','countProjects'],['articles','countArticles'],['messages','countMessages']]){const {count}=await supabase.from(t).select('*',{count:'exact',head:true}); if($('#'+id))$('#'+id).textContent=count??0} loadLists()}
async function loadLists(){const p=await supabase.from('projects').select('*').order('created_at',{ascending:false}); $('#projectAdminList').innerHTML=(p.data||[]).map(x=>`<div class="row"><b>${x.title}</b><span>${x.slug}</span></div>`).join('');const a=await supabase.from('articles').select('*').order('created_at',{ascending:false});$('#articleAdminList').innerHTML=(a.data||[]).map(x=>`<div class="row"><b>${x.title}</b><span>${x.published?'Published':'Draft'}</span></div>`).join('')}
$('#projectForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const tags=f.get('tags').split(',').map(x=>x.trim()).filter(Boolean);const {error}=await supabase.from('projects').insert({title:f.get('title'),slug:f.get('slug'),description:f.get('description'),url:f.get('url'),problem:f.get('problem'),solution:f.get('solution'),build:f.get('build'),cover_image:f.get('cover_image'),tags});alert(error?error.message:'Project saved');if(!error){e.target.reset();loadCounts()}};
$('#articleForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await supabase.from('articles').insert({title:f.get('title'),slug:f.get('slug'),excerpt:f.get('excerpt'),content:f.get('content'),cover_image:f.get('cover_image'),tags:f.get('tags').split(',').map(x=>x.trim()).filter(Boolean),medium_url:f.get('medium_url'),published:f.has('published'),published_at:f.has('published')?new Date().toISOString():null});alert(error?error.message:'Article saved');if(!error){e.target.reset();loadCounts()}};
$$('form[data-simple]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form), obj=Object.fromEntries(f.entries());obj.published=f.has('published');const table=form.dataset.simple;const {error}=await supabase.from(table).insert(obj);alert(error?error.message:`Saved to ${table}`);if(!error)form.reset()});
session();