import {supabase} from "./supabase.js";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const obj=f=>Object.fromEntries(new FormData(f).entries());
const tags=v=>String(v||"").split(",").map(x=>x.trim()).filter(Boolean);
function toast(m){const t=$("#toast");t.textContent=m;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),2600)}
async function auth(){const {data:{session}}=await supabase.auth.getSession();if(!session)return false;const {data}=await supabase.from("admin_profiles").select("*").eq("id",session.user.id).maybeSingle();if(!data||data.role!=="admin"){await supabase.auth.signOut();return false}$("#login").classList.add("hidden");$("#app").classList.remove("hidden");return true}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error){$("#error").textContent=error.message;return}if(!(await auth()))$("#error").textContent="Account is not the single authorized admin."});
$("#logout").onclick=async()=>{await supabase.auth.signOut();location.reload()};
$$(".admin-nav button").forEach(b=>b.onclick=()=>{$$(".admin-nav button").forEach(x=>x.classList.remove("active"));$$(".admin-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab).classList.add("active")});
async function count(t){const {count}=await supabase.from(t).select("*",{count:"exact",head:true});return count??0}
async function dashboard(){$("#cp").textContent=await count("projects");$("#ca").textContent=await count("articles");$("#cf").textContent=await count("feed_posts");$("#cm").textContent=await count("messages");rows()}
async function rows(){const {data:p}=await supabase.from("projects").select("title,slug,published").order("created_at",{ascending:false});$("#projectRows").innerHTML=(p||[]).map(x=>`<div class="row"><span><b>${esc(x.title)}</b><br><small>${esc(x.slug)}</small></span><span class="badge">${x.published?"Published":"Draft"}</span></div>`).join("")||"<p class='admin-sub'>No projects.</p>";const {data:a}=await supabase.from("articles").select("title,slug,published").order("created_at",{ascending:false});$("#articleRows").innerHTML=(a||[]).map(x=>`<div class="row"><span><b>${esc(x.title)}</b><br><small>${esc(x.slug)}</small></span><span class="badge">${x.published?"Published":"Draft"}</span></div>`).join("")||"<p class='admin-sub'>No articles.</p>";const {data:m}=await supabase.from("messages").select("*").order("created_at",{ascending:false});$("#messagesList").innerHTML=(m||[]).map(x=>`<article class="row" style="display:block"><b>${esc(x.name||"Anonymous")}</b> · ${esc(x.email||"")}<p>${esc(x.message||"")}</p></article>`).join("")||"<p class='admin-sub'>No messages.</p>"}
async function save(table,p,form,msg="Saved."){const {error}=await supabase.from(table).insert(p);toast(error?error.message:msg);if(!error){form.reset();dashboard()}}
$("#homeForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target);const {error}=await supabase.from("site_settings").upsert({key:"homepage",value:f,updated_at:new Date().toISOString()});toast(error?error.message:"Homepage saved.")};
$("#projectForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target);await save("projects",{title:f.title,slug:f.slug,description:f.description,problem:f.problem,solution:f.solution,build:f.build,cover_image:f.cover_image,url:f.url,tags:tags(f.tags),published:e.target.published.checked},e.target,"Project saved.")};
$("#articleForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target),published=e.target.published.checked;await save("articles",{title:f.title,slug:f.slug,excerpt:f.excerpt,content:f.content,cover_image:f.cover_image,tags:tags(f.tags),medium_url:f.medium_url,published,published_at:published?new Date().toISOString():null},e.target,"Article saved.")};
$("#feedForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target);await save("feed_posts",{title:f.title,content:f.content,tags:tags(f.tags)},e.target,"Feed posted.")};
$("#labForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target);await save("labs",{title:f.title,slug:f.slug,description:f.description,url:f.url},e.target,"Lab saved.")};
$("#achievementForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target);await save("achievements",{title:f.title,date:f.date,description:f.description},e.target,"Achievement saved.")};
$("#pageForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target);await save("pages",{title:f.title,slug:f.slug,content:f.content},e.target,"Page saved.")};
$("#contributorForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target);await save("contributors",{name:f.name,slug:f.slug,bio:f.bio,profile_image:f.profile_image,url:f.url},e.target,"Contributor saved.")};
$("#mediaForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target);await save("media",{title:f.title,url:f.url,credit:f.credit},e.target,"Media saved.")};
$("#handleForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target);await save("handles",{platform:f.platform,label:f.label,url:f.url},e.target,"Handle saved.")};
$("#seoForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target);await save("seo_metadata",{path:f.path,title:f.title,description:f.description,og_image:f.og_image,indexable:e.target.indexable.checked},e.target,"SEO saved.")};
$("#settingForm").onsubmit=async e=>{e.preventDefault();const f=obj(e.target);let value;try{value=JSON.parse(f.value)}catch{toast("Invalid JSON.");return}const {error}=await supabase.from("site_settings").upsert({key:f.key,value,updated_at:new Date().toISOString()});toast(error?error.message:"Setting saved.");if(!error)e.target.reset()};
if(await auth()){dashboard();const {data}=await supabase.from("site_settings").select("value").eq("key","homepage").maybeSingle();if(data?.value){const v=typeof data.value==="string"?JSON.parse(data.value):data.value;$("#homeForm").hero_title.value=v.hero_title||"";$("#homeForm").currently.value=v.currently||"";$("#homeForm").current_copy.value=v.current_copy||""}}
