create extension if not exists pgcrypto;
create table if not exists admin_profiles(id uuid primary key references auth.users(id) on delete cascade,name text not null,handle text,role text default 'admin',created_at timestamptz default now());
create table if not exists projects(id uuid primary key default gen_random_uuid(),title text not null,slug text unique not null,description text,problem text,solution text,build text,cover_image text,url text,tags text[] default '{}',published boolean default false,created_at timestamptz default now());
create table if not exists articles(id uuid primary key default gen_random_uuid(),title text not null,slug text unique not null,excerpt text,content text,cover_image text,tags text[] default '{}',medium_url text,published boolean default false,published_at timestamptz,created_at timestamptz default now());
create table if not exists feed_posts(id uuid primary key default gen_random_uuid(),title text not null,content text,tags text[] default '{}',created_at timestamptz default now());
create table if not exists labs(id uuid primary key default gen_random_uuid(),title text not null,slug text unique,description text,url text,created_at timestamptz default now());
create table if not exists achievements(id uuid primary key default gen_random_uuid(),title text not null,date text,description text,created_at timestamptz default now());
create table if not exists pages(id uuid primary key default gen_random_uuid(),title text not null,slug text unique,content text,created_at timestamptz default now());
create table if not exists contributors(id uuid primary key default gen_random_uuid(),name text not null,slug text unique, bio text,profile_image text,url text,created_at timestamptz default now());
create table if not exists media(id uuid primary key default gen_random_uuid(),title text,url text,credit text,created_at timestamptz default now());
create table if not exists handles(id uuid primary key default gen_random_uuid(),platform text not null,label text,url text,created_at timestamptz default now());
create table if not exists seo_metadata(id uuid primary key default gen_random_uuid(),path text unique not null,title text,description text,og_image text,indexable boolean default true,created_at timestamptz default now());
create table if not exists site_settings(key text primary key,value jsonb default '{}'::jsonb,updated_at timestamptz default now());
create table if not exists messages(id uuid primary key default gen_random_uuid(),name text,email text,message text,read boolean default false,created_at timestamptz default now());
alter table admin_profiles enable row level security; alter table projects enable row level security; alter table articles enable row level security; alter table feed_posts enable row level security; alter table labs enable row level security; alter table achievements enable row level security; alter table pages enable row level security; alter table contributors enable row level security; alter table media enable row level security; alter table handles enable row level security; alter table seo_metadata enable row level security; alter table site_settings enable row level security; alter table messages enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from admin_profiles where id=auth.uid() and role='admin'); $$;
create policy "public published projects" on projects for select using (published=true or public.is_admin());
create policy "admin projects" on projects for all using (public.is_admin()) with check (public.is_admin());
create policy "public published articles" on articles for select using (published=true or public.is_admin());
create policy "admin articles" on articles for all using (public.is_admin()) with check (public.is_admin());
create policy "admin all feed" on feed_posts for all using (public.is_admin()) with check (public.is_admin());
create policy "admin all labs" on labs for all using (public.is_admin()) with check (public.is_admin());
create policy "admin all achievements" on achievements for all using (public.is_admin()) with check (public.is_admin());
create policy "admin all pages" on pages for all using (public.is_admin()) with check (public.is_admin());
create policy "public contributors" on contributors for select using (true);
create policy "admin contributors" on contributors for all using (public.is_admin()) with check (public.is_admin());
create policy "admin all media" on media for all using (public.is_admin()) with check (public.is_admin());
create policy "public handles" on handles for select using (true);
create policy "admin handles" on handles for all using (public.is_admin()) with check (public.is_admin());
create policy "public seo" on seo_metadata for select using (true);
create policy "admin seo" on seo_metadata for all using (public.is_admin()) with check (public.is_admin());
create policy "public settings" on site_settings for select using (true);
create policy "admin settings" on site_settings for all using (public.is_admin()) with check (public.is_admin());
create policy "admin messages" on messages for all using (public.is_admin()) with check (public.is_admin());
create policy "admin profile self" on admin_profiles for select using (auth.uid()=id);
insert into contributors(name,slug,bio) values('Oparah Nation','oparah-nation','Visual contributor and creative collaborator.') on conflict(slug) do nothing;
insert into site_settings(key,value) values('homepage','{"currently":"Building digital products.","current_copy":"Writing, learning and exploring new ideas."}') on conflict(key) do nothing;